name: CI

on: [push]

jobs:

  build:
    strategy:
      matrix:
        image: ["yard", "proto-swagger", "redoc"]

    runs-on: ubuntu-latest

    env:
      DOCKER_REPO: apidocgen/${{ matrix.image }}
      DOCKER_TAG: ${{ github.sha }}

    steps:
    - uses: actions/checkout@v1
    - run: docker build ${{ matrix.image }} --tag ${DOCKER_REPO}:${DOCKER_TAG}
    - run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login --username "${{ secrets.DOCKER_USERNAME }}" --password-stdin
    - run: docker push ${DOCKER_REPO}:${DOCKER_TAG}
    - run: |
        docker ${DOCKER_REPO}:latest ${DOCKER_REPO}:${DOCKER_TAG}
        docker push ${DOCKER_REPO}:latest
      if: github.ref == 'refs/heads/master'
    - run: |
        tag=$(echo ${{ github.ref }} | sed 's!refs/tags/yard/!!')
        docker ${DOCKER_REPO}:${tag} ${DOCKER_REPO}:${DOCKER_TAG}
        docker push ${DOCKER_REPO}:${tag}
      if: startsWith(github.ref, format('refs/tags/{0}', matrix.image))
